" based on http://github.com/jferris/config_files/blob/master/vimrc
" also based on Janus

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" \ is the default leader character, set it to SPACEBAR instead
let mapleader=' '

" Numbers
set number
set numberwidth=5

" show the cursor position all the time
set ruler		

" Set encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
" set list listchars=tab:\ \ ,trail:·
" set list listchars=tab:»·,trail:·

" Set syntax folding to automatic but unfolded by default
set foldmethod=syntax
set foldlevelstart=99

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Status bar
set laststatus=2

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Without setting this, ZoomWin restores windows in a way that causes
" equalalways behavior to be triggered the next time CommandT is used.
" This is likely a bludgeon to solve some other issue, but it works
set noequalalways

" NERDTree configuration
let NERDTreeIgnore=['\.pyc$', '\.rbc$', '\~$']
map <Leader>n :NERDTreeToggle<CR>

" Command-T configuration
let g:CommandTMaxHeight=20

" ZoomWin configuration
map <Leader><Leader> :ZoomWin<CR>

" CTags
map <Leader>rt :!ctags --extra=+f -R *<CR><CR>
map <C-\> :tnext<CR>

" Remember last location in file
if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
endif

function s:setupWrapping()
  set wrap
  set wrapmargin=2
  set textwidth=72
endfunction

function s:setupMarkup()
  call s:setupWrapping()
  map <buffer> <Leader>p :Hammer<CR>
endfunction

" Thorfile, Rakefile, Vagrantfile and Gemfile are Ruby
au BufRead,BufNewFile {Gemfile,Rakefile,Vagrantfile,Thorfile,config.ru}    set ft=ruby

" md, markdown, and mk are markdown and define buffer-local preview
au BufRead,BufNewFile *.{md,markdown,mdown,mkd,mkdn} call s:setupMarkup()

" add json syntax highlighting
au BufNewFile,BufRead *.json set ft=javascript

au BufRead,BufNewFile *.txt call s:setupWrapping()

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" load the plugin and indent settings for the detected filetype
filetype plugin indent on

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Unimpaired configuration
" Bubble single lines
nmap <C-Up> [e
nmap <C-Down> ]e
" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Enable syntastic syntax checking
let g:syntastic_enable_signs=1
let g:syntastic_quiet_warnings=1

" gist-vim defaults
if has("mac")
  let g:gist_clip_command = 'pbcopy'
elseif has("unix")
  let g:gist_clip_command = 'xclip -selection clipboard'
endif
let g:gist_detect_filetype = 1
let g:gist_open_browser_after_post = 1

" Use modeline overrides
set modeline
set modelines=10

" Default color scheme
color desert

" Directories for swp files
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Turn off jslint errors by default
let g:JSLintHighlightErrorLine = 0

" MacVIM shift+arrow-keys behavior (required in .vimrc)
let macvim_hig_shift_movement = 1

" % to bounce from do to end etc.
runtime! macros/matchit.vim

" Show (partial) command in the status line
set showcmd

" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif

" END OF JANUS
"
" set nobackup
" set nowritebackup
" set history=250		" keep 250 lines of command line history
" set incsearch		" do incremental searching

" Edit the README_FOR_APP (makes :R commands work)
" map <Leader>R :e doc/README_FOR_APP<CR>

" Leader shortcuts for Rails commands
" map <Leader>m :Rmodel 
" map <Leader>c :Rcontroller 
" map <Leader>v :Rview 
" map <Leader>u :Runittest 
" map <Leader>f :Rfunctionaltest 
" map <Leader>tm :RTmodel 
" map <Leader>tc :RTcontroller 
" map <Leader>tv :RTview 
" map <Leader>tu :RTunittest 
" map <Leader>tf :RTfunctionaltest 
" map <Leader>sm :RSmodel 
" map <Leader>sc :RScontroller 
" map <Leader>sv :RSview 
" map <Leader>su :RSunittest 
" map <Leader>sf :RSfunctionaltest 

" Hide search highlighting
" map <Leader>h :set invhls <CR>

" Opens an edit command with the path of the currently edited file filled in
" Normal mode: <Leader>e
" map <Leader>e :e <C-R>=expand("%:p:h") . "/" <CR>

" Opens a tab edit command with the path of the currently edited file filled in
" Normal mode: <Leader>t
" map <Leader>te :tabe <C-R>=expand("%:p:h") . "/" <CR>

" Inserts the path of the currently edited file into a command
" Command mode: Ctrl+P
" cmap <C-P> <C-R>=expand("%:p:h") . "/" <CR>

" Duplicate a selection
" Visual mode: D
" vmap D y'>p

" Press Shift+P while in visual mode to replace the selection without
" overwriting the default register
" vmap P p :call setreg('"', getreg('0')) <CR>

" For Haml
" au! BufRead,BufNewFile *.haml         setfiletype haml

" Yank from the cursor to the end of the line, to be consistent with C and D.
" nnoremap Y y$

" No Help, please
" nmap <F1> <Esc>

" Press ^F from insert mode to insert the current file name
" imap <C-F> <C-R>=expand("%")<CR>

" Maps autocomplete to tab
" imap <Tab> <C-N>

" imap <C-L> <Space>=><Space>

" Display extra whitespace
" set list listchars=tab:»·,trail:·

" Edit routes
" command! Rroutes :e config/routes.rb
" command! Rschema :e db/schema.rb

" Local config
" if filereadable(".vimrc.local")
"   source .vimrc.local
" endif

" Use Ack instead of Grep when available
" if executable("ack")
"   set grepprg=ack\ -H\ --nogroup\ --nocolor\ --ignore-dir=tmp\ --ignore-dir=coverage
" endif

" Now folded into .gvimrc
" Color scheme
" colorscheme ir_black
" colorscheme vividchalk
" highlight NonText guibg=#060606
" highlight Folded  guibg=#0A0A0A guifg=#9090D0

" Snippets are activated by Shift+Tab
" let g:snippetsEmu_key = "<S-Tab>"

" Tab completion options
" (only complete to the longest unambiguous match, and show a menu)
" set completeopt=longest,menu
" set wildmode=list:longest,list:full
" set complete=.,t

" case only matters with mixed case expressions
" set ignorecase
" set smartcase

" Tags
" let g:Tlist_Ctags_Cmd="ctags --exclude='*.js'"
" set tags=./tags;

" let g:fuf_splitPathMatching=1

" Open URL
" command -bar -nargs=1 OpenURL :!open <args>
" function! OpenURL()
"   let s:uri = matchstr(getline("."), '[a-z]*:\/\/[^ >,;:]*')
"   echo s:uri
"   if s:uri != ""
" 	  exec "!open \"" . s:uri . "\""
"   else
" 	  echo "No URI found in line."
"   endif
" endfunction
" map <Leader>w :call OpenURL()<CR>

"Easy empty line insertion in normal mode
" nnoremap <Return> o<Esc>k0
" nnoremap <S-Return> O<Esc>j0

" Customize mappings for RubyTest.vim
" map <D-R> <Plug>RubyTestRun   
" map <D-r> <Plug>RubyFileRun    
" map <D-i> <Plug>RubyTestRunLast
" let g:rubytest_in_quickfix = 1

" Mappings for ruby_focused_unit_test.vim
" map <silent> <Leader>rb :RunAllRubyTests<CR>
" map <silent> <Leader>rc :RunRubyFocusedContext<CR>
" map <silent> <Leader>rf :RunRubyFocusedUnitTest<CR>

" window
" nmap <leader>swh :topleft  vnew<CR>
" nmap <leader>swl :botright vnew<CR>
" nmap <leader>swk :topleft  new<CR>
" nmap <leader>swj :botright new<CR>
" buffer
" nmap <leader>sh :leftabove  vnew<CR>
" nmap <leader>sl :rightbelow vnew<CR>
" nmap <leader>sk :leftabove  new<CR>
" nmap <leader>sj :rightbelow new<CR>
